import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = dirname(fileURLToPath(import.meta.url));
const expert = 'https://experts.deakin.edu.au/37446-bipasha-kashyap';
const nav = [['index.html','About'],['research.html','Research'],['instruments.html','Instruments'],['publications.html','Publications'],['teaching.html','Teaching & Service'],['achievements.html','Achievements']];
const escape = text => text.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const papers = [
  {year:2026,title:'Quantifying Dimensional Independence in Speech: An Information-Theoretic Framework for Disentangled Representation Learning',authors:'Bipasha Kashyap, Bjorn W. Schuller, Pubudu N. Pathirana',venue:'arXiv:2602.20592. Preprint.',url:'https://arxiv.org/abs/2602.20592',label:'Preprint'},
  {year:2025,title:'Quantum Approaches for Dysphonia Assessment in Small Speech Datasets',authors:'Ha Tran, Bipasha Kashyap, Pubudu N. Pathirana',venue:'IEEE Engineering in Medicine and Biology Society (EMBC)',doi:'10.1109/EMBC58623.2025.11252849'},
  {year:2025,title:'Image encoded time series classification of small datasets: an innovative architecture using deep learning ensembles',authors:'Pubudu L. Indrasiri, Bipasha Kashyap, Pubudu N. Pathirana',venue:'International Journal of Machine Learning and Cybernetics',doi:'10.1007/s13042-025-02613-0'},
  {year:2024,title:'FedXPro: Bayesian Inference for Mitigating Poisoning Attacks in IoT Federated Learning',authors:'Pubudu L. Indrasiri, Dinh C. Nguyen, Bipasha Kashyap, Pubudu N. Pathirana, Yonina C. Eldar',venue:'IEEE Internet of Things Journal',doi:'10.1109/JIOT.2023.3334298'},
  {year:2023,title:'Machine Learning-Based Scoring System to Predict the Risk and Severity of Ataxic Speech Using Different Speech Tasks',authors:'Bipasha Kashyap, Pubudu N. Pathirana, Malcolm Horne, Laura Power, David J. Szmulewicz',venue:'IEEE Transactions on Neural Systems and Rehabilitation Engineering',doi:'10.1109/TNSRE.2023.3334718'},
  {year:2021,title:'Modeling the Progression of Speech Deficits in Cerebellar Ataxia Using a Mixture Mixed-Effect Machine Learning Framework',authors:'Bipasha Kashyap, Pubudu N. Pathirana, Malcolm Horne, Laura Power, David J. Szmulewicz',venue:'IEEE Access',doi:'10.1109/ACCESS.2021.3114328'},
  {year:2020,title:'Objective Assessment of Cerebellar Ataxia: A Comprehensive and Refined Approach',authors:'Bipasha Kashyap, Dung Phan, Pubudu N. Pathirana, Malcolm Horne, Laura Power, David Szmulewicz',venue:'Scientific Reports',doi:'10.1038/s41598-020-65303-7'},
  {year:2020,title:'Quantitative Assessment of Speech in Cerebellar Ataxia Using Magnitude and Phase Based Cepstrum',authors:'Bipasha Kashyap, Pubudu N. Pathirana, Malcolm Horne, Laura Power, David Szmulewicz',venue:'Annals of Biomedical Engineering',doi:'10.1007/s10439-020-02455-7'},
  {year:2020,title:'Automated Topographic Prominence based quantitative assessment of speech timing in Cerebellar Ataxia',authors:'Bipasha Kashyap, Malcolm Horne, Pubudu N. Pathirana, Laura Power, David Szmulewicz',venue:'Biomedical Signal Processing and Control',doi:'10.1016/j.bspc.2019.101759',demo:'prominence.html'}
];
const publication = p => `<article class="publication"><h3><a href="${p.url || 'https://doi.org/'+p.doi}">${escape(p.title)}</a></h3><p class="authors">${escape(p.authors).replace('Bipasha Kashyap','<strong>Bipasha Kashyap</strong>')}</p><p class="venue"><em>${escape(p.venue)}</em> &middot; ${p.year}</p><div class="publication-links"><a href="${p.url || 'https://doi.org/'+p.doi}">${p.label || 'DOI'}</a>${p.demo ? `<a href="${p.demo}">Related demonstration</a>` : ''}</div></article>`;
const contact = `<section class="contact" id="contact"><h2>Get in touch</h2><p>For research collaborations and enquiries about graduate research in speech processing, machine learning or sensing:</p><a href="mailto:b.kashyap@deakin.edu.au">b.kashyap@deakin.edu.au</a></section>`;
function page(file,title,content,description){
  writeFileSync(join(root,file),`<!doctype html>
<html lang="en-AU"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(title)} | Dr Bipasha Kashyap</title><meta name="description" content="${escape(description)}"><meta name="theme-color" content="#006e68"><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="style.css"></head>
<body><a class="skip" href="#main">Skip to content</a><header class="masthead"><a class="brand" href="index.html"><span class="monogram" aria-hidden="true">bk</span>Bipasha Kashyap</a><nav class="nav" aria-label="Main navigation">${nav.map(([url,label])=>`<a href="${url}"${file===url?' aria-current="page"':''}>${escape(label)}</a>`).join('')}</nav></header>
<div class="layout"><aside class="profile" aria-label="Researcher profile"><img class="portrait" src="portrait.jpg" alt="Dr Bipasha Kashyap" width="180" height="180"><div class="profile-detail"><div class="profile-name">Dr Bipasha Kashyap</div><p>Lecturer, Mechatronics<br>Deakin University</p><p>Deputy Director<br>NSBE Research Lab</p></div><div class="profile-links"><a href="mailto:b.kashyap@deakin.edu.au">Email</a><a href="${expert}">Deakin profile</a><a href="https://orcid.org/0000-0002-9469-858X">ORCID</a><a href="https://github.com/BipashaK2020">GitHub</a></div><div class="profile-label">Based in</div><div class="affiliation">School of Engineering<br>Geelong, Australia</div></aside><main id="main">${content}</main></div><footer class="footer"><span>&copy; 2026 Bipasha Kashyap</span><span>Speech &middot; Information &middot; Sensing</span><a href="mailto:b.kashyap@deakin.edu.au">Contact</a></footer></body></html>\n`);
}

page('index.html','About',`
<p class="kicker">Speech signal processing &amp; machine learning</p><h1>Dr Bipasha Kashyap</h1><p class="role-line">Lecturer &middot; Researcher &middot; Graduate Research Coordinator</p>
<p class="intro">I study how information is encoded in signals, with a current focus on human speech.</p>
<p>My research asks how emotional, linguistic and physiological information can be characterised and separated within a single acoustic signal. I combine signal processing, information theory and machine learning, with applications in accent fairness in automatic speech recognition and quantitative clinical speech assessment.</p>
<p>I am a Lecturer in Mechatronics at Deakin University, Deputy Director of the Networked Sensing and Biomedical Engineering Lab, and Graduate Research Coordinator in the School of Engineering. My PhD research examined quantitative assessment of speech in cerebellar ataxia.</p>
<p><a href="research.html">Research projects</a> &nbsp;&middot;&nbsp; <a href="publications.html">Selected publications</a></p>
<section class="section"><div class="section-head"><h2>Research interests</h2></div><div class="two-col"><div class="topic"><h3>Information in speech</h3><p>Understanding relationships between speech dimensions, and how representations retain or confound information.</p><a href="research.html#encoding">Encoding &amp; representation</a></div><div class="topic"><h3>Signals into measurements</h3><p>Quantifying speech timing, vocal characteristics and movement through acoustic and sensor measurements.</p><a href="research.html#assessment">Speech &amp; sensing</a></div></div></section>
<section class="section"><div class="section-head"><h2>Research instruments</h2><a href="instruments.html">All five instruments &rarr;</a></div><div class="two-col"><div><span class="tag">Speech &middot; 5 seconds</span><h3><a href="prominence.html">Speech timing</a></h3><p class="muted">Explore syllable peaks, pauses and rhythm in a short speech recording.</p></div><div><span class="tag">Voice &middot; sustained vowel</span><h3><a href="phonation.html">Sustained vowel</a></h3><p class="muted">Explore pitch, phonation time and acoustic variation in a sustained sound.</p></div></div><p class="muted" style="font-size:14px">Research demonstrations, not medical devices.</p></section>
<section class="section"><h2>Recent work</h2><ul class="news"><li><time datetime="2026-02">Feb 2026</time><p><a href="https://arxiv.org/abs/2602.20592">Quantifying Dimensional Independence in Speech</a>, a preprint with Bjorn W. Schuller and Pubudu N. Pathirana.</p></li><li><time datetime="2026-01">Jan 2026</time><p>Graduate Research Coordinator, School of Engineering, Deakin University.</p></li><li><time datetime="2025">2025</time><p><a href="https://doi.org/10.1109/EMBC58623.2025.11252849">Quantum approaches for dysphonia assessment</a>, with Ha Tran and Pubudu N. Pathirana, at IEEE EMBC.</p></li></ul></section>${contact}`,
'Dr Bipasha Kashyap researches speech signal processing, information theory and machine learning at Deakin University.');

page('research.html','Research',`<p class="kicker">Research</p><h1>Information in human signals</h1><p class="intro">Understanding what a signal contains, what a model uses, and what a measurement can tell us.</p>
<figure class="research-figure"><img src="speech-research.webp" width="1200" height="675" alt="Conceptual illustration of a speech waveform separating into several information streams through a prism"><figcaption>A conceptual view of multidimensional information in speech.</figcaption></figure>
<article class="project" id="encoding"><span class="tag">Current research</span><h2>Dimensional encoding in speech</h2><p>Speech carries several kinds of information through the same acoustic channel. My work investigates statistical relationships between emotional, linguistic and physiological dimensions, using mutual-information estimation and source-filter analysis.</p><p>Accent fairness in automatic speech recognition and clinical speech assessment provide complementary settings for evaluating whether methods generalise across speakers and tasks.</p><p class="project-meta">With Bjorn W. Schuller and Pubudu N. Pathirana</p><div class="project-links"><a href="https://arxiv.org/abs/2602.20592">2026 preprint</a><a href="publications.html">Publications</a></div></article>
<article class="project" id="assessment"><span class="tag">PhD research &amp; subsequent publications</span><h2>Quantitative speech assessment</h2><p>My research on cerebellar ataxia examines objective measures of speech timing and vocal characteristics. This includes topographic prominence for syllable detection, magnitude- and phase-based cepstral analysis, and models of changes in speech over time.</p><p class="project-meta">With Pubudu N. Pathirana, Malcolm Horne, Laura Power and David Szmulewicz</p><div class="project-links"><a href="https://doi.org/10.1016/j.bspc.2019.101759">Speech timing paper</a><a href="prominence.html">Speech timing demonstration</a></div></article>
<article class="project"><span class="tag">Collaborative research &middot; IEEE EMBC 2025</span><h2>Quantum learning for voice assessment</h2><p>With Ha Tran and Pubudu N. Pathirana, I investigated hybrid quantum-classical neural networks for dysphonia assessment in small speech datasets, comparing these approaches with convolutional models.</p><div class="project-links"><a href="https://doi.org/10.1109/EMBC58623.2025.11252849">Read the paper</a></div></article>
<article class="project"><span class="tag">Collaborative research</span><h2>Learning from sensor data</h2><p>Related work explores time-series image encoding, deep-learning ensembles and federated learning for sensor systems. These projects connect signal representation with practical constraints such as limited datasets and unreliable model updates.</p><div class="project-links"><a href="https://doi.org/10.1007/s13042-025-02613-0">Time-series classification</a><a href="https://doi.org/10.1109/JIOT.2023.3334298">FedXPro</a><a href="instruments.html">Sensing demonstrations</a></div></article>
<section class="section"><span class="tag">Future directions</span><h2>Filtering and controlled synthesis</h2><p>I am interested in filters that reduce unwanted confounds while preserving task-relevant information, and in testing separation through controlled speech resynthesis. These are proposed research directions building on the dimensional-encoding work.</p></section>${contact}`,
'Research in speech information, quantitative speech assessment, quantum machine learning and sensor data.');

const instruments = [
 ['01','Speech timing','prominence.html','Speech','Record a short passage and examine syllable peaks, pauses and timing.','Syllable count, speech rate, pause ratio, rhythm variability.','Microphone / 5 seconds'],
 ['02','Sustained vowel','phonation.html','Voice','Examine acoustic characteristics of a sustained vowel.','Phonation time, pitch, jitter, shimmer and harmonics-to-noise ratio.','Microphone / up to 30 seconds'],
 ['03','Tremor spectrum','tremor.html','Movement','Explore a movement recording as a time trace and frequency spectrum.','Motion amplitude and spectral content.','Phone motion sensor / 10 seconds'],
 ['04','Finger tapping','tapping.html','Motor timing','Record repeated taps and examine the intervals between them.','Tap count, rate, rhythm variability and change in rate.','Touch, mouse or keyboard / 15 seconds'],
 ['05','Fingertip pulse','pulse.html','Optical sensing','Explore changes in light recorded by a camera beneath a fingertip.','Estimated pulse rate, beat count and beat-to-beat variability.','Rear camera / 30 seconds']
];
page('instruments.html','Instruments',`<p class="kicker">Interactive research demonstrations</p><h1>Five small instruments</h1><p class="intro">Speech, movement and pulse signals, measured in the browser.</p><p>These demonstrations connect signal-processing methods with observable recordings. The speech instruments sit alongside three explorations of movement, timing and optical sensing.</p><div class="instrument-list">${instruments.map(([n,title,url,category,description,measures,requirements])=>`<article class="instrument"><span class="instrument-number" aria-hidden="true">${n}</span><div><span class="tag">${category}</span><h2 style="font-size:24px"><a href="${url}">${title}</a></h2><p>${description}</p><p class="measure-list">${measures}</p><p class="requirements">${requirements}</p></div><a class="instrument-link" href="${url}" aria-label="Open ${title}">Open instrument &rarr;</a></article>`).join('')}</div><section class="section"><h2>About the measurements</h2><p>These are research demonstrations, not medical devices. Their estimates depend on recording conditions and device hardware and should not be used to diagnose or monitor a medical condition.</p><p>Recordings are processed in the browser by these demos. Microphone, camera and motion access are requested only when an instrument is started. Sensor access requires a supported device and a secure connection.</p><p>The speech-timing demonstration is related to the <a href="https://doi.org/10.1016/j.bspc.2019.101759">topographic prominence research</a>; the browser implementation is not the validated clinical study system.</p></section>`,
'Five research demonstrations for speech timing, sustained vowel analysis, tremor, finger tapping and fingertip pulse.');

let previousYear;
page('publications.html','Publications',`<p class="kicker">Research outputs</p><h1>Selected publications</h1><p>Selected work on speech, machine learning and sensing. The <a href="${expert}/publications">Deakin research record</a> includes further publications.</p>${papers.map(p=>{const heading=p.year!==previousYear?`<h2 class="pub-year">${p.year}</h2>`:'';previousYear=p.year;return heading+publication(p);}).join('')}`,
'Selected publications by Bipasha Kashyap, with DOI links and related research demonstrations.');

page('teaching.html','Teaching & Service',`<p class="kicker">Academic practice</p><h1>Teaching &amp; service</h1><p class="intro">Teaching across signal processing, electronics, connected systems and engineering design.</p><section class="section"><h2>Teaching</h2><div class="table-wrap"><table><thead><tr><th scope="col">Unit</th><th scope="col">Subject</th></tr></thead><tbody><tr><td>SEE312</td><td>Data Communication</td></tr><tr><td>SEE711</td><td>IoT Systems Engineering</td></tr><tr><td>SEE712</td><td>Applied Signal Processing</td></tr><tr><td>SEN721</td><td>Engineering Design</td></tr><tr><td>SEE216</td><td>Analogue and Digital Systems</td></tr></tbody></table></div><p class="muted" style="font-size:14px;margin-top:16px">My curriculum development includes IoT Systems Engineering and Applied Signal Processing.</p></section>
<section class="section"><h2>Academic leadership</h2><ul class="plain-list"><li>Graduate Research Coordinator, School of Engineering, Deakin University.</li><li>Deputy Director, Networked Sensing and Biomedical Engineering Research Lab.</li><li>Fellow of the Higher Education Academy, UK.</li></ul></section><section class="section"><h2>Research supervision</h2><p>I supervise research in speech processing, machine learning and sensing, including Master's and PhD projects. Prospective students can contact me with their research interests and background.</p><a href="${expert}/teaching">Deakin teaching &amp; supervision profile</a></section>
<section class="section"><h2>Peer review</h2><p>My reviewing includes the following journals:</p><ul class="plain-list"><li>IEEE Transactions on Neural Systems and Rehabilitation Engineering</li><li>IEEE Internet of Things Journal</li><li>IEEE Journal of Selected Topics in Signal Processing</li><li>Computers in Biology and Medicine</li><li>Frontiers in Neurology</li><li>npj Digital Medicine</li></ul></section>${contact}`,
'Teaching, academic leadership, supervision and reviewing by Dr Bipasha Kashyap.');

page('achievements.html','Achievements',`<p class="kicker">Grants &amp; recognition</p><h1>Selected achievements</h1><p class="intro">Research support, teaching recognition and science communication.</p><ul class="timeline"><li><time>2025</time><div><h3>MAAP Linkage Grant</h3><p>Co-Lead Investigator. Real-time stress detection from biosignals in virtual reality.</p></div></li><li><time>2024</time><div><h3>Fellow of the Higher Education Academy</h3><p>Advance HE, United Kingdom.</p></div></li><li><time>2024</time><div><h3>PRESS ECR Grant</h3><p>Lead Investigator. Telehealth research for speech disorders.</p></div></li><li><time>2023</time><div><h3>Minor Equipment Scheme</h3><p>Principal Investigator.</p></div></li><li><time>2020</time><div><h3>Visualise Your Thesis</h3><p>Deakin first place and People's Choice; international finalist.</p></div></li><li><time>2020</time><div><h3>FameLab</h3><p>Victoria semi-finalist.</p></div></li><li><time>2017&ndash;21</time><div><h3>CSIRO Data61 PhD scholarship</h3><p>Doctoral research at Deakin University.</p></div></li><li><time>2016&ndash;17</time><div><h3>veski Victorian Fellowship</h3><p>Support for professional development and research.</p></div></li></ul><section class="section"><h2>Science communication</h2><p>Public engagement includes a 2020 RRR Radio feature on speech and neural health, an invited Ignite presentation at IEEE EMBC in Hawaii in 2018, and participation in the Women in Science Think Tank at Government House Melbourne.</p></section>`,
'Selected research grants, fellowships, awards and science communication by Bipasha Kashyap.');

writeFileSync(join(root,'404.html'),'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page not found | Bipasha Kashyap</title><body style="font:18px/1.6 Arial,sans-serif;max-width:620px;margin:80px auto;padding:24px"><h1>Page not found</h1><p>The page may have moved.</p><a href="/bipashak/">Return to Bipasha Kashyap\'s website</a></body></html>');
console.log('Built six academic pages and a 404 page.');
