import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = dirname(fileURLToPath(import.meta.url));
const expert = 'https://experts.deakin.edu.au/37446-bipasha-kashyap';
const nav = [['index.html','About'],['research.html','Research Projects'],['publications.html','Publications'],['supervision.html','Team'],['achievements.html','Achievements'],['teaching.html','Teaching & Services'],['talks.html','Seminars'],['instruments.html','Instruments']];
const escape = text => text.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const papers = [
  {year:2026,title:'Quantifying Dimensional Independence in Speech: An Information-Theoretic Framework for Disentangled Representation Learning',authors:'Bipasha Kashyap, Bjoern Schuller, Pubudu N. Pathirana',venue:'Interspeech 2026, pp. 5543-5547',doi:'10.21437/Interspeech.2026-1654',url:'https://www.isca-archive.org/interspeech_2026/kashyap26_interspeech.html',label:'Proceedings'},
  {year:2025,title:'Quantum Approaches for Dysphonia Assessment in Small Speech Datasets',authors:'Ha Tran, Bipasha Kashyap, Pubudu N. Pathirana',venue:'IEEE Engineering in Medicine and Biology Society (EMBC)',doi:'10.1109/EMBC58623.2025.11252849'},
  {year:2025,title:'Image encoded time series classification of small datasets: an innovative architecture using deep learning ensembles',authors:'Pubudu L. Indrasiri, Bipasha Kashyap, Pubudu N. Pathirana',venue:'International Journal of Machine Learning and Cybernetics',doi:'10.1007/s13042-025-02613-0'},
  {year:2024,title:'FedXPro: Bayesian Inference for Mitigating Poisoning Attacks in IoT Federated Learning',authors:'Pubudu L. Indrasiri, Dinh C. Nguyen, Bipasha Kashyap, Pubudu N. Pathirana, Yonina C. Eldar',venue:'IEEE Internet of Things Journal',doi:'10.1109/JIOT.2023.3334298'},
  {year:2023,title:'Machine Learning-Based Scoring System to Predict the Risk and Severity of Ataxic Speech Using Different Speech Tasks',authors:'Bipasha Kashyap, Pubudu N. Pathirana, Malcolm Horne, Laura Power, David J. Szmulewicz',venue:'IEEE Transactions on Neural Systems and Rehabilitation Engineering',doi:'10.1109/TNSRE.2023.3334718'},
  {year:2021,title:'Modeling the Progression of Speech Deficits in Cerebellar Ataxia Using a Mixture Mixed-Effect Machine Learning Framework',authors:'Bipasha Kashyap, Pubudu N. Pathirana, Malcolm Horne, Laura Power, David J. Szmulewicz',venue:'IEEE Access',doi:'10.1109/ACCESS.2021.3114328'},
  {year:2020,title:'Objective Assessment of Cerebellar Ataxia: A Comprehensive and Refined Approach',authors:'Bipasha Kashyap, Dung Phan, Pubudu N. Pathirana, Malcolm Horne, Laura Power, David Szmulewicz',venue:'Scientific Reports',doi:'10.1038/s41598-020-65303-7'},
  {year:2020,title:'Quantitative Assessment of Speech in Cerebellar Ataxia Using Magnitude and Phase Based Cepstrum',authors:'Bipasha Kashyap, Pubudu N. Pathirana, Malcolm Horne, Laura Power, David Szmulewicz',venue:'Annals of Biomedical Engineering',doi:'10.1007/s10439-020-02455-7'},
  {year:2020,title:'Automated Topographic Prominence based quantitative assessment of speech timing in Cerebellar Ataxia',authors:'Bipasha Kashyap, Malcolm Horne, Pubudu N. Pathirana, Laura Power, David Szmulewicz',venue:'Biomedical Signal Processing and Control',doi:'10.1016/j.bspc.2019.101759',demo:'prominence.html'}
];
papers.push(
  {year:2024,title:'Harnessing Vision Transformer Insights for Advanced Electrocardiogram Classification',authors:'Pubudu L. Indrasiri, Bipasha Kashyap, Pubudu N. Pathirana',venue:'IEEE EMBC',doi:'10.1109/EMBC53108.2024.10782430'},
  {year:2023,title:'A Study of Upper-Limb Motion using Kinematic Measures for Clinical Assessment of Cerebellar Ataxia',authors:'Lahiru L. Abeysekara, Bipasha Kashyap, Chandima Kolambahewage, Pubudu N. Pathirana, Malcolm Horne, David J. Szmulewicz',venue:'IEEE EMBC',doi:'10.1109/EMBC40787.2023.10340741'},
  {year:2023,title:'An Enhanced Classification Framework for Limited IoHT Time Series Data Using Ensemble Deep Learning and Image Encoding',authors:'Pubudu L. Indrasiri, Bipasha Kashyap, Pubudu N. Pathirana',venue:'IEEE EMBC',doi:'10.1109/EMBC40787.2023.10341070'},
  {year:2023,title:'Federated Learning with Provable Security Against Malicious Clients in IoT Networks',authors:'Pubudu L. Indrasiri, Dinh C. Nguyen, Bipasha Kashyap, Pubudu N. Pathirana',venue:'IEEE Virtual Conference on Communications',doi:'10.1109/VCC60689.2023.10474836'},
  {year:2020,title:'A Sensor-Based Comprehensive Objective Assessment of Motor Symptoms in Cerebellar Ataxia',authors:'Bipasha Kashyap, Dung Phan, Pubudu N. Pathirana, Malcolm Horne, Laura Power, David Szmulewicz',venue:'IEEE EMBC',doi:'10.1109/EMBC44109.2020.9175887'},
  {year:2019,title:'Automated tongue-twister phrase-based screening for Cerebellar Ataxia using Vocal tract Biomarkers',authors:'Bipasha Kashyap, Pubudu N. Pathirana, Malcolm Horne, Laura Power, David Szmulewicz',venue:'IEEE EMBC',doi:'10.1109/EMBC.2019.8857868'},
  {year:2018,title:'Quantitative Assessment of Syllabic Timing Deficits in Ataxic Dysarthria',authors:'Bipasha Kashyap, Pubudu N. Pathirana, Malcolm Horne, Laura Power, David Szmulewicz',venue:'IEEE EMBC',doi:'10.1109/EMBC.2018.8512311'},
  {year:2017,title:'A constrained nonlinear optimization solution for 3D orientation estimation of the human limb',authors:'Dung Phan, Bipasha Kashyap, Pubudu N. Pathirana, Aruna Seneviratne',venue:'Biomedical Engineering International Conference (BMEiCON)',doi:'10.1109/BMEiCON.2017.8229138'},
  {year:2017,title:'Identification of Cerebellar Dysarthria with SISO Characterisation',authors:'Bipasha Kashyap, David Szmulewicz, Pubudu N. Pathirana, Malcolm Horne, Laura Power',venue:'IEEE International Conference on Bioinformatics and Bioengineering, pp. 479-485',doi:'10.1109/BIBE.2017.000-8'}
);
papers.sort((a,b)=>b.year-a.year);
const publication = p => `<article class="publication"><h3><a href="${p.url || 'https://doi.org/'+p.doi}">${escape(p.title)}</a></h3><p class="authors">${escape(p.authors).replace('Bipasha Kashyap','<strong>Bipasha Kashyap</strong>')}</p><p class="venue"><em>${escape(p.venue)}</em> &middot; ${p.year}</p><div class="publication-links"><a href="${p.url || 'https://doi.org/'+p.doi}">${p.label || 'DOI'}</a>${p.demo ? `<a href="${p.demo}">Related demonstration</a>` : ''}</div></article>`;
const contact = `<section class="contact" id="contact"><h2>Get in touch</h2><p>For research collaborations and enquiries about graduate research in speech processing, machine learning or sensing:</p><a href="mailto:b.kashyap@deakin.edu.au">b.kashyap@deakin.edu.au</a></section>`;
function page(file,title,content,description){
  const home = file === 'index.html';
  const hero = home ? `<section class="hero" aria-labelledby="hero-title"><img src="speech-research.webp" alt="A speech waveform separating into information streams through a prism" width="1200" height="675" fetchpriority="high"><div class="hero-copy"><h1 id="hero-title">Bipasha Kashyap</h1><h2>Speech, Information &amp; Sensing</h2><p>Understanding how information is encoded in human signals.</p></div></section>` : '';
  const profile = home ? `<section class="profile-intro" aria-label="Researcher profile"><div><h2>Dr Bipasha Kashyap</h2><p class="profile-role">Lecturer, Mechatronics &middot; Deakin University</p><p class="profile-role">Deputy Director, NSBE Research Lab<br>Graduate Research Coordinator, School of Engineering</p><p><a href="mailto:b.kashyap@deakin.edu.au">b.kashyap@deakin.edu.au</a></p><div class="profile-links"><a href="${expert}">University Profile</a><a href="https://orcid.org/0000-0002-9469-858X">ORCID</a><a href="https://github.com/BipashaK2020">GitHub</a></div><p class="research-keywords">Signal Processing &middot; Information Theory &middot; Machine Learning<br>Accent Fairness &middot; Clinical Speech Assessment</p></div><img class="portrait" src="portrait.jpg" alt="Dr Bipasha Kashyap" width="180" height="180"></section>` : '';
  writeFileSync(join(root,file),`<!doctype html>
<html lang="en-AU"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(title)} | Dr Bipasha Kashyap</title><meta name="description" content="${escape(description)}"><meta name="theme-color" content="#222222"><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="style.css"><script src="site.js" defer></script></head>
<body class="academic-page ${home?'home-page':''}"><a class="skip" href="#main">Skip to content</a><header class="masthead"><div class="nav-inner"><a class="brand" href="index.html">Bipasha Kashyap</a><button class="menu-toggle" type="button" aria-label="Toggle navigation" aria-expanded="false" aria-controls="main-nav" title="Toggle navigation"><img src="menu.svg" alt="" width="24" height="24"></button><nav class="nav" id="main-nav" aria-label="Main navigation">${nav.map(([url,label])=>`<a href="${url}"${file===url?' aria-current="page"':''}>${escape(label)}</a>`).join('')}</nav></div></header>
${hero}<main class="layout" id="main">${profile}${content}</main><footer class="footer"><span>&copy; 2026 Bipasha Kashyap</span><a href="mailto:b.kashyap@deakin.edu.au">Contact</a></footer></body></html>\n`);
}

page('index.html','About',`
<h2 class="section-title">About</h2>
<p class="intro">I study how information is encoded in signals, with a current focus on human speech.</p>
<p>My research asks how emotional, linguistic and physiological information can be characterised and separated within a single acoustic signal. I combine signal processing, information theory and machine learning, with applications in accent fairness in automatic speech recognition and quantitative clinical speech assessment.</p>
<p>I am a Lecturer in Mechatronics at Deakin University, Deputy Director of the Networked Sensing and Biomedical Engineering Lab, and Graduate Research Coordinator in the School of Engineering. My PhD research examined quantitative assessment of speech in cerebellar ataxia.</p>
<p>Engineering should improve lives, teaching should build capability, and leadership should enable both. This principle guides my research, teaching and work with students.</p>
<p><a href="research.html">Research projects</a> &nbsp;&middot;&nbsp; <a href="publications.html">Selected publications</a></p>
<section class="section"><div class="section-head"><h2>Research interests</h2></div><div class="two-col"><div class="topic"><h3>Information in speech</h3><p>Understanding relationships between speech dimensions, and how representations retain or confound information.</p><a href="research.html#encoding">Encoding &amp; representation</a></div><div class="topic"><h3>Signals into measurements</h3><p>Quantifying speech timing, vocal characteristics and movement through acoustic and sensor measurements.</p><a href="research.html#assessment">Speech &amp; sensing</a></div></div></section>
<section class="section"><div class="section-head"><h2>Research instruments</h2><a href="instruments.html">All five instruments &rarr;</a></div><div class="two-col"><div><span class="tag">Speech &middot; 5 seconds</span><h3><a href="prominence.html">Speech timing</a></h3><p class="muted">Explore syllable peaks, pauses and rhythm in a short speech recording.</p></div><div><span class="tag">Voice &middot; sustained vowel</span><h3><a href="phonation.html">Sustained vowel</a></h3><p class="muted">Explore pitch, phonation time and acoustic variation in a sustained sound.</p></div></div><p class="muted" style="font-size:14px">Research demonstrations, not medical devices.</p></section>
<section class="section"><h2>News</h2><ul class="news"><li><time datetime="2026-09">Sept 2026</time><p><a href="https://www.isca-archive.org/interspeech_2026/kashyap26_interspeech.html">Quantifying Dimensional Independence in Speech</a> appears in the Interspeech 2026 proceedings, with Bj&ouml;rn Schuller and Pubudu N. Pathirana. Presentation and session chairing are scheduled for the Sydney conference, 27 September&ndash;1 October.</p></li><li><time datetime="2026">2026</time><p>Led a School of Engineering Three Minute Thesis training initiative for higher-degree researchers.</p></li><li><time datetime="2026-01">Jan 2026</time><p>Graduate Research Coordinator, School of Engineering, Deakin University.</p></li><li><time datetime="2025">2025</time><p><a href="https://doi.org/10.1109/EMBC58623.2025.11252849">Quantum approaches for dysphonia assessment</a>, with Ha Tran and Pubudu N. Pathirana, at IEEE EMBC.</p></li></ul></section>${contact}`,
'Dr Bipasha Kashyap researches speech signal processing, information theory and machine learning at Deakin University.');

page('research.html','Research',`<p class="kicker">Research</p><h1>Research Projects</h1><p class="intro">Understanding what a signal contains, what a model uses, and what a measurement can tell us.</p>
<figure class="research-figure"><img src="speech-research.webp" width="1200" height="675" alt="Conceptual illustration of a speech waveform separating into several information streams through a prism"><figcaption>A conceptual view of multidimensional information in speech.</figcaption></figure>
<div class="project-grid"><article class="project" id="assessment"><span class="tag">Project 1 &middot; Completed PhD research, 2017&ndash;2021</span><h2>Dysarthria and speech-motor assessment in cerebellar ataxia</h2><p>Developing objective, quantitative measures of speech-motor impairment to complement clinical assessment. My doctoral work combined acoustic and cepstral features with machine-learning models of speech characteristics and change over time.</p><p>Methods include topographic prominence for syllable detection, magnitude- and phase-based cepstral analysis, and mixed-effect modelling of longitudinal recordings. Subsequent collaborative publications extend the work to movement assessment.</p><p class="project-meta">With Pubudu N. Pathirana, Malcolm Horne, Laura Power and David Szmulewicz. Doctoral support: CSIRO Data61 scholarship.</p><div class="project-links"><a href="https://doi.org/10.1038/s41598-020-65303-7">Comprehensive assessment</a><a href="https://doi.org/10.1016/j.bspc.2019.101759">Speech timing</a><a href="https://doi.org/10.1109/ACCESS.2021.3114328">Longitudinal modelling</a><a href="prominence.html">Speech timing demonstration</a></div></article>
<article class="project" id="quantum"><span class="tag">Project 2 &middot; Collaborative research</span><h2>Quantum machine learning for quantitative healthcare assessment</h2><p>Exploring hybrid quantum-classical architectures for dysphonia assessment in small speech datasets, with comparisons against convolutional models.</p><p class="project-meta">With Ha Tran and Pubudu N. Pathirana. Published output: IEEE EMBC 2025.</p><div class="project-links"><a href="https://doi.org/10.1109/EMBC58623.2025.11252849">Dysphonia assessment paper</a></div></article>
<article class="project" id="encoding"><span class="tag">Project 3 &middot; Current research</span><h2>Spectro-temporal characterisation of dimensional encoding</h2><p>Investigating where emotional, linguistic and physiological information is represented within speech, and how strongly these dimensions are statistically related.</p><p>I combine mutual-information estimation with source-filter analysis. The methods include MINE and CLUB bounds, a non-parametric KSG cross-check, and cepstral attribution. Accent fairness in automatic speech recognition and clinical speech assessment are complementary application domains.</p><p>The Interspeech 2026 paper reports an initial framework; broader spectro-temporal characterisation remains ongoing.</p><p class="project-meta">With Bj&ouml;rn Schuller and Pubudu N. Pathirana.</p><div class="project-links"><a href="https://www.isca-archive.org/interspeech_2026/kashyap26_interspeech.html">Interspeech 2026 paper</a><a href="https://doi.org/10.21437/Interspeech.2026-1654">DOI</a></div></article>
<article class="project" id="filtering"><span class="tag">Project 4 &middot; Proposed research</span><h2>Information-theoretic dimensional filtering</h2><p>Investigating filters that suppress accent- or emotion-related confounds while preserving information needed by a specified task.</p><p>Planned methods include cepstral liftering, mutual-information minimisation, variational decomposition and rate-distortion analysis. This direction builds on the dimensional-encoding work; it is not yet a completed research output.</p></article>
<article class="project" id="synthesis"><span class="tag">Project 5 &middot; Proposed research</span><h2>Synthesis-based validation of the encoding framework</h2><p>Testing separation methods through controlled speech resynthesis: changing one dimension and examining how the other dimensions respond.</p><p>Planned work combines WORLD-vocoder synthesis with acoustic fidelity measures and listening studies. Any participant study will require ethics approval before it begins.</p></article></div>
<section class="section"><h2>Other published research</h2><h3>Federated learning and IoT security</h3><p>Collaborative work examines resilience to unreliable and malicious model updates in distributed learning. Collaborators include Pubudu L. Indrasiri, Dinh C. Nguyen, Pubudu N. Pathirana and Yonina C. Eldar.</p><div class="project-links"><a href="https://doi.org/10.1109/JIOT.2023.3334298">FedXPro</a><a href="https://doi.org/10.1109/VCC60689.2023.10474836">Security against malicious clients</a></div>
<h3 style="margin-top:28px">Vision transformers and time-series classification</h3><p>With Pubudu L. Indrasiri and Pubudu N. Pathirana, I explore image representations, deep-learning ensembles and vision transformers for small time-series datasets, including ECG and connected-health signals.</p><div class="project-links"><a href="https://doi.org/10.1007/s13042-025-02613-0">Time-series classification</a><a href="https://doi.org/10.1109/EMBC53108.2024.10782430">ECG classification</a><a href="https://doi.org/10.1109/EMBC40787.2023.10341070">Limited IoHT datasets</a></div></section>
<section class="section"><h2>Research engineering</h2><p>During my postdoctoral work at the NSBE Research Lab in 2021&ndash;2022, I contributed AI development and AWS engineering to BioKin AIMs, a sensor-based assessment platform. This experience informed my interest in how signal-processing methods generalise across recordings and populations.</p><p><a href="instruments.html">Explore the browser-based research demonstrations</a></p></section>${contact}`,
'Research projects in speech-motor assessment, quantum learning, dimensional encoding, filtering, synthesis and sensor systems.');

const instruments = [
 ['01','Speech timing','prominence.html','Speech','Record a short passage and examine syllable peaks, pauses and timing.','Syllable count, speech rate, pause ratio, rhythm variability.','Microphone / 5 seconds'],
 ['02','Sustained vowel','phonation.html','Voice','Examine acoustic characteristics of a sustained vowel.','Phonation time, pitch, jitter, shimmer and harmonics-to-noise ratio.','Microphone / up to 30 seconds'],
 ['03','Tremor spectrum','tremor.html','Movement','Explore a movement recording as a time trace and frequency spectrum.','Motion amplitude and spectral content.','Phone motion sensor / 10 seconds'],
 ['04','Finger tapping','tapping.html','Motor timing','Record repeated taps and examine the intervals between them.','Tap count, rate, rhythm variability and change in rate.','Touch, mouse or keyboard / 15 seconds'],
 ['05','Fingertip pulse','pulse.html','Optical sensing','Explore changes in light recorded by a camera beneath a fingertip.','Estimated pulse rate, beat count and beat-to-beat variability.','Rear camera / 30 seconds']
];
page('instruments.html','Instruments',`<p class="kicker">Interactive research demonstrations</p><h1>Five small instruments</h1><p class="intro">Speech, movement and pulse signals, measured in the browser.</p><p>These demonstrations connect signal-processing methods with observable recordings. The speech instruments sit alongside three explorations of movement, timing and optical sensing.</p><div class="instrument-list">${instruments.map(([n,title,url,category,description,measures,requirements])=>`<article class="instrument"><span class="instrument-number" aria-hidden="true">${n}</span><div><span class="tag">${category}</span><h2 style="font-size:24px"><a href="${url}">${title}</a></h2><p>${description}</p><p class="measure-list">${measures}</p><p class="requirements">${requirements}</p></div><a class="instrument-link" href="${url}" aria-label="Open ${title}">Open instrument &rarr;</a></article>`).join('')}</div><section class="section"><h2>About the measurements</h2><p>These are research demonstrations, not medical devices. Their estimates depend on recording conditions and device hardware and should not be used to diagnose or monitor a medical condition.</p><p>Recordings are processed in the browser by these demos. Microphone, camera and motion access are requested only when an instrument is started. Sensor access requires a supported device and a secure connection.</p><p>The speech-timing demonstration is related to the <a href="https://doi.org/10.1016/j.bspc.2019.101759">topographic prominence research</a>; the browser implementation is not the validated clinical study system.</p></section>`,
'Five research demonstrations for speech timing, sustained vowel analysis, tremor, finger tapping and fingertip pulse.');

let previousYear;
page('publications.html','Publications',`<p class="kicker">Research outputs</p><h1>Publications</h1><p>18 journal and conference publications in speech, machine learning and sensing. Preprints and the doctoral thesis are not included in this list.</p><p><a href="${expert}/publications">Deakin research record</a> &nbsp;&middot;&nbsp; <a href="publications.bib" download>Download citations (.bib)</a></p>${papers.map(p=>{const heading=p.year!==previousYear?`<h2 class="pub-year">${p.year}</h2>`:'';previousYear=p.year;return heading+publication(p);}).join('')}`,
'Publications by Bipasha Kashyap, with DOI links, citations and related research demonstrations.');
writeFileSync(join(root,'publications.bib'),papers.map((p,i)=>`@misc{kashyap${p.year}_${i+1},\n  title = {{${p.title}}},\n  author = {${p.authors.replace(', et al.', ', others').split(', ').join(' and ')}},\n  year = {${p.year}},\n  howpublished = {${p.venue}},\n  ${p.doi?'doi = {'+p.doi+'}':'url = {'+p.url+'}'}\n}`).join('\n\n')+'\n');

page('teaching.html','Teaching & Service',`<p class="kicker">Academic practice</p><h1>Teaching &amp; service</h1><p class="intro">Teaching across signal processing, electronics, connected systems and engineering design.</p><section class="section"><h2>Teaching</h2><div class="table-wrap"><table><thead><tr><th scope="col">Unit</th><th scope="col">Subject</th></tr></thead><tbody><tr><td>SEE312</td><td>Data Communications</td></tr><tr><td>SEE711</td><td>IoT Systems Engineering</td></tr><tr><td>SEE712</td><td>Applied Signal Processing</td></tr><tr><td>&mdash;</td><td>Engineering Design</td></tr><tr><td>SEE216</td><td>Analogue and Digital Electronics</td></tr></tbody></table></div><p class="muted" style="font-size:14px;margin-top:16px">My curriculum development includes IoT Systems Engineering and Applied Signal Processing.</p></section>
<section class="section"><h2>Teaching approach</h2><p>In IoT Systems Engineering and Applied Signal Processing, students collect their own sensor data and carry it through processing, analysis and deployment using industry-standard software and hardware.</p><p>I use staged assessments, shared rubrics and feedforward feedback. Deakin's Learning Analytics for Teachers helps me monitor engagement and adapt teaching during the trimester. From 2026, high-weighted tasks include a live component in which students run and defend their work on their own data.</p><p>My approach to assessment flexibility uses evidence of progress to support students while maintaining academic standards.</p></section>
<section class="section"><h2>Academic leadership</h2><ul class="plain-list"><li>Graduate Research Coordinator, School of Engineering, Deakin University.</li><li>Deputy Director, Networked Sensing and Biomedical Engineering Research Lab.</li><li>Fellow of the Higher Education Academy, UK.</li></ul></section><section class="section"><h2>Research supervision</h2><p>I supervise research in speech processing, machine learning and sensing, including Master's and PhD projects. Prospective students can contact me with their research interests and background.</p><a href="${expert}/teaching">Deakin teaching &amp; supervision profile</a></section>
<section class="section"><h2>Peer review</h2><p>My reviewing includes the following journals and conference:</p><ul class="plain-list"><li>IEEE Transactions on Neural Systems and Rehabilitation Engineering</li><li>IEEE Internet of Things Journal</li><li>IEEE Journal of Selected Topics in Signal Processing</li><li>Computers in Biology and Medicine</li><li>Frontiers in Neurology</li><li>npj Digital Medicine</li><li>Interspeech 2026</li></ul></section>
<section class="section"><h2>Professional memberships</h2><ul class="plain-list"><li>Australasian Speech Science and Technology Association (ASSTA).</li><li>IEEE.</li><li>Affiliate Member, IEEE Signal Processing Society Speech and Language Processing Technical Committee (SLTC).</li></ul></section>
<section class="section"><h2>Assessment development</h2><p>In 2025, I contributed to the Faculty of Science, Engineering and Built Environment's Redefining Assessment Transformation project, working with colleagues across four engineering disciplines and Deakin's FutureLearn team on authentic, AI-aware assessment design.</p></section>${contact}`,
'Teaching, academic leadership, supervision and reviewing by Dr Bipasha Kashyap.');

page('achievements.html','Achievements',`<p class="kicker">Grants &amp; recognition</p><h1>Selected achievements</h1><p class="intro">Research support, teaching recognition and science communication.</p><ul class="timeline"><li><time>2026</time><div><h3>Research communication training</h3><p>Led a School of Engineering Three Minute Thesis training initiative, co-facilitated with colleagues.</p></div></li><li><time>2025</time><div><h3>MAAP Linkage Grant</h3><p>Co-Lead Investigator. Real-time stress detection from biosignals in virtual reality.</p></div></li><li><time>2024</time><div><h3>Fellow of the Higher Education Academy</h3><p>Advance HE, United Kingdom.</p></div></li><li><time>2024</time><div><h3>PRESS ECR Grant</h3><p>Lead Investigator. Telehealth research for speech disorders.</p></div></li><li><time>2023</time><div><h3>Mini ARC Discovery research support</h3><p>Two internal awards supporting federated learning for smart health and AI for emotional states in virtual reality.</p></div></li><li><time>2023</time><div><h3>Minor Equipment Scheme</h3><p>Principal Investigator.</p></div></li><li><time>2020&ndash;21</time><div><h3>Codan industry grant</h3><p>Lead Investigator.</p></div></li><li><time>2020</time><div><h3>Visualise Your Thesis</h3><p>Deakin first place and People's Choice; international finalist.</p></div></li><li><time>2020</time><div><h3>FameLab</h3><p>Victoria semi-finalist.</p></div></li><li><time>2017&ndash;21</time><div><h3>CSIRO Data61 PhD scholarship</h3><p>Doctoral research at Deakin University.</p></div></li><li><time>2016&ndash;17</time><div><h3>veski Victorian Fellowship</h3><p>Support for professional development and research.</p></div></li></ul><section class="section"><h2>Science communication</h2><p>Public engagement includes a 2020 RRR Radio feature on speech and neural health, an invited Ignite presentation at IEEE EMBC in Hawaii in 2018, and participation in the Women in Science Think Tank at Government House Melbourne.</p></section>`,
'Selected research grants, fellowships, awards and science communication by Bipasha Kashyap.');

writeFileSync(join(root,'404.html'),'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page not found | Bipasha Kashyap</title><body style="font:18px/1.6 Arial,sans-serif;max-width:620px;margin:80px auto;padding:24px"><h1>Page not found</h1><p>The page may have moved.</p><a href="/bipashak/">Return to Bipasha Kashyap\'s website</a></body></html>');
page('supervision.html','Supervision',`<p class="kicker">Graduate research</p><h1>Team &amp; Supervision</h1><p class="intro">Research across speech, biomedical signals and machine learning systems.</p><p>As Graduate Research Coordinator in Deakin's School of Engineering and Deputy Director of the NSBE Research Lab, I contribute to doctoral supervision and the wider research community.</p><section class="section"><h2>Mentoring and lab culture</h2><p>I established a weekly research seminar series within the NSBE Research Lab, giving students a regular forum to present work in progress and receive feedback.</p><p>In 2026, I led a Three Minute Thesis training initiative for the School's higher-degree researchers, co-facilitated with three colleagues. The programme combined a presentation framework, insights from past winners, a cross-disciplinary academic panel and a live demonstration.</p></section><section class="section"><h2>Current doctoral research</h2><p>My current supervision spans four project areas:</p><ul class="plain-list"><li>Quantum machine learning for quantitative healthcare assessment.</li><li>AI and machine learning for biomedical signals and images.</li><li>Workload optimisation in cloud and edge computing.</li><li>Multimodal sensing of fatigue through sweat and gait biomarkers.</li></ul><a href="${expert}/teaching">Current supervision record at Deakin</a></section><section class="section"><h2>Completed research</h2><p>Completed doctoral supervision includes work on data security, scarcity and efficacy in the Internet of Things, completed in 2026. Related outputs include research on federated learning and time-series classification.</p><a href="publications.html">Related publications</a></section><section class="section"><h2>Research collaborations</h2><p>My collaborative research includes work with Bj&ouml;rn Schuller on dimensional independence in speech and Yonina C. Eldar on robust federated learning.</p><div class="project-links"><a href="https://www.isca-archive.org/interspeech_2026/kashyap26_interspeech.html">Speech representation research</a><a href="https://doi.org/10.1109/JIOT.2023.3334298">FedXPro</a></div></section><section class="section"><h2>Prospective students</h2><p>I welcome enquiries from students interested in signal processing, information theory, speech and machine learning. Please include a short outline of your interests and your academic background.</p><p><a href="mailto:b.kashyap@deakin.edu.au?subject=Graduate%20research%20enquiry">Contact me about graduate research</a></p><a href="https://www.deakin.edu.au/research/research-degrees-and-phd">Research degrees at Deakin</a></section>`,'Graduate research supervision in speech processing, machine learning and sensing at Deakin University.');

page('talks.html','Talks & Engagement',`<p class="kicker">Talks &amp; engagement</p><h1>Seminars &amp; Engagement</h1><p class="intro">Research presentations, science communication and public engagement.</p><ul class="timeline"><li><time>Upcoming<br>Sept&ndash;Oct 2026</time><div><h3>Interspeech 2026, Sydney</h3><p>Scheduled presentation of paper 1654, &ldquo;Quantifying Dimensional Independence in Speech&rdquo;, and session chairing. Conference: 27 September&ndash;1 October 2026.</p><a href="https://www.isca-archive.org/interspeech_2026/kashyap26_interspeech.html">Conference paper</a></div></li><li><time>2026</time><div><h3>Three Minute Thesis training</h3><p>Led and co-facilitated a School of Engineering training initiative for higher-degree researchers, including a live demonstration and cross-disciplinary feedback.</p></div></li><li><time>Ongoing</time><div><h3>NSBE research seminars</h3><p>Established a weekly seminar series for students to share work in progress and receive feedback.</p></div></li><li><time>2020</time><div><h3>Our speech, a reporter of our neural health</h3><p>Radio interview for Einstein A Go-Go, RRR. 3 May 2020.</p></div></li><li><time>2020</time><div><h3>Visualise Your Thesis</h3><p>Research communication presentation. Deakin first place and People's Choice; international finalist.</p></div></li><li><time>2019</time><div><h3>Three Minute Thesis</h3><p>Third finalist in Deakin's Faculty of Science, Engineering and Built Environment semi-finals.</p></div></li><li><time>2018</time><div><h3>Ignite presentation</h3><p>Invited speaker at IEEE Engineering in Medicine and Biology Society, Hawaii.</p></div></li><li><time>2017</time><div><h3>Women in Science Think Tank</h3><p>International Women's Day event at Government House Melbourne. 8 March 2017.</p></div></li><li><time>2016</time><div><h3>Engineers Australia meeting</h3><p>Presentation of Master's research on functional observers for interconnected systems. 6 June 2016.</p></div></li></ul><p><a href="${expert}/professional">Professional activities at Deakin</a></p>${contact}`,'Research talks, science communication and public engagement by Dr Bipasha Kashyap.');
console.log('Built eight academic pages, 18 publication citations and a 404 page.');
